[package]
name = "wasixcc"
version = "0.4.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/wasix-org/wasixcc"
description = "C/C++ compiler for the WASIX platform"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

# wasixccenv, the management tool for wasixcc, is the default executable
# that handles installation etc., so we want that to be the default binary.
[[bin]]
name = "wasixccenv"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
regex = "1.11.1"
tempfile = "3.20.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# Required for the sysroot download
flate2 = "1.1.2"
tar = "0.4.44"
serde = { version = "1.0.219", features = ["derive"] }

# Pinned dependencies for WASIX builds
getrandom = "0.3.3"
reqwest = { version = "0.12.22", features = [
    "blocking",
    "charset",
    "h2",
    "http2",
    "json",
    "rustls-tls",
], default-features = false }
tower = "0.5.2"
tower-layer = "0.3.3"
tower-service = "0.3.3"
fs_extra = "1.3.0"
shell-words = "1.1.1"
rustls-native-certs = "0.8.1"
webpki-roots = "1.0.4"
rustls = "0.23.35"
clap = { version = "4.5.50", features = ["derive", "wrap_help"] }

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
    'cfg(target_vendor, values("wasmer"))',
] }
